default:
    tags:
        - windows

variables:
    RUSTC_WRAPPER: sccache

build:
    stage: build
    script:
        - scripts/build.ps1 -config debug
        - scripts/build.ps1 -config release
    only:
        - master
        - merge_requests
        - tags
    artifacts:
        paths:
            - bin/debug/*.exe
            - bin/debug/*.dll
            - bin/debug/thirdparty/*.exe
            - bin/release/*.exe
            - bin/release/*.dll
            - bin/release/thirdparty/*.exe
            - thirdparty/directxtex-2020.9.30/*.exe
cache:
    paths:
        - bin/**/thirdparty/
        - build/**/thirdparty/