CREATE TABLE character
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_username varchar(20) NOT NULL,
    -- General
    name varchar(30) NOT NULL UNIQUE,
    gender_id smallint NOT NULL DEFAULT 0,
    job_id smallint NOT NULL DEFAULT 0,
    face_id integer NOT NULL DEFAULT 1,
    hair_id integer NOT NULL DEFAULT 1,
    -- Stats
    level smallint NOT NULL DEFAULT 1,
    exp int NOT NULL DEFAULT 0,
    hp int NOT NULL DEFAULT 100,
    mp int NOT NULL DEFAULT 100,
    stamina int NOT NULL DEFAULT 5000,
    max_hp int NOT NULL DEFAULT 100,
    max_mp int NOT NULL DEFAULT 100,
    max_stamina int NOT NULL DEFAULT 5000,
    str smallint NOT NULL DEFAULT 15,
    dex smallint NOT NULL DEFAULT 15,
    intt smallint NOT NULL DEFAULT 15,
    con smallint NOT NULL DEFAULT 10,
    cha smallint NOT NULL DEFAULT 10,
    sen smallint NOT NULL DEFAULT 10,
    -- Economy
    money bigint NOT NULL DEFAULT 0,
    storage_money bigint NOT NULL DEFAULT 0,
    -- World
    map_id smallint NOT NULL DEFAULT(22),
    respawn_x real NOT NULL DEFAULT(577987.99),
    respawn_y real NOT NULL DEFAULT(515579.9805),
    town_respawn_id smallint NOT NULL DEFAULT(22),
    town_respawn_x real NOT NULL DEFAULT(577987.99),
    town_respawn_y real NOT NULL DEFAULT(515579.9805),
    -- Meta
    created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    delete_by timestamptz,
    CONSTRAINT character_level_positive CHECK (level > 0),
    CONSTRAINT character_money_positive CHECK (money >= 0),
    CONSTRAINT character_storage_money_positive CHECK (storage_money >= 0)
);

CREATE TABLE item
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_data_id integer NOT NULL DEFAULT 0,
    grade integer NOT NULL DEFAULT 0,
    CONSTRAINT grade_positive CHECK (grade >= 0)
);

CREATE TABLE equipment
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    character_id integer NOT NULL DEFAULT 0 REFERENCES character (id) ON DELETE CASCADE,
    item_id integer NOT NULL DEFAULT 0 REFERENCES item (id) ON DELETE SET DEFAULT,
    slot varchar(5) NOT NULL,
    UNIQUE (character_id, item_id, slot),
    CONSTRAINT equipment_slot_valid CHECK (slot in ('head', 'chest', 'arms', 'feet', 'face', 'back', 'lhand', 'rhand'))
);

CREATE TABLE worldvar
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL UNIQUE,
    data jsonb NOT NULL,
    modified TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);