CREATE TABLE account
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username varchar(20) NOT NULL UNIQUE,
    password char(32) NOT NULL,
    access_level INTEGER NOT NULL DEFAULT 0,
    email varchar(30) NOT NULL UNIQUE,
    created TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);