[package]
name = "pipeline"
version = "0.1.0"
authors = ["Ralph Minderhoud <ralphminderhoud@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2"
clap = "2.33"
roselib = {path = "../../thirdparty/rose-lib"}
serde = { version = "1", features = ["derive"] }