// Automatically generated by cbindgen. DO NOT MODIFY.

#include <cstdarg>
#include <cstdint>
#include <cstdlib>

namespace Rose {
namespace Common {

enum class LogLevel {
  Trace,
  Debug,
  Info,
  Warn,
  Error,
  Off,
};

extern "C" {

void logger_init(LogLevel level);

void logger_write(LogLevel level, const char *msg);

} // extern "C"

} // namespace Common
} // namespace Rose
