// Automatically generated by cbindgen. DO NOT MODIFY.

#include <cstdarg>
#include <cstdint>
#include <cstdlib>

namespace Rose {
namespace Common {

extern "C" {

bool get_bin_dir(char *path, size_t size);

} // extern "C"

} // namespace Common
} // namespace Rose
