extern crate cbindgen;


fn main() {
  let warning = "// Automatically generated by cbindgen. DO NOT MODIFY.";

  cbindgen::Builder::new()
    .with_src("src/ffi/logger.rs")
    .with_namespaces(&["Rose", "Common"])
    .with_autogen_warning(warning)
    .generate()
    .expect("Unable to generate bindings")
    .write_to_file("include/rose/common/log.h");

  cbindgen::Builder::new()
    .with_src("src/ffi/util.rs")
    .with_namespaces(&["Rose", "Common"])
    .with_autogen_warning(warning)
    .generate()
    .expect("Unable to generate bindings")
    .write_to_file("include/rose/common/util.h");
}