[package]
name = "rose-common"
version = "0.1.0"
authors = ["Ralph Minderhoud <ralphminderhoud@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib"]

[build-dependencies]
cbindgen = "0.8"

[dependencies]
lazy_static = "1.3"
libc = "0.2"
log = "0.4"
